version: '3.8'

services:
  backend:
    container_name: account
    image: account-dev
    build:
      context: .
      dockerfile: docker/nest/Dockerfile.dev
    volumes:
      - .:/improve
    env_file:
      - docker/nest/docker.env
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manage_hub

  pgadmin:
    build: ./docker/database
    ports:
      - '5050:80'
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_SERVER_JSON_PATH: /var/lib/pgadmin/servers.json
      PGADMIN_SERVER_JSON_FILE: /var/lib/pgadmin/servers.json
      PGADMIN_SERVER_JSON_ENCRYPTION_KEY: 'my-secret-key-12345'
