version: "3.8"

services:
  backend:
    container_name: account
    image: account-dev
    # restart: unless-stopped
    build:
      context: .
      dockerfile: docker/nest/Dockerfile
      target: dev
    # command: tail -f /dev/null
    env_file:
      - docker/nest/docker.env
    ports:
      - "3000:3000"
