version: '3.8'

services:
  backend:
    container_name: account
    image: account-dev
    build:
      context: .
      dockerfile: docker/nest/Dockerfile.dev
    volumes:
      - .:/improve
    env_file:
      - docker/nest/docker.env
    ports:
      - '3000:3000'
