version: '3.8'

services:
  backend:
    container_name: account
    image: account-dev
    build:
      context: .
      dockerfile: docker/nest/Dockerfile.dev
    volumes:
      - .:/improve
    env_file:
      - docker/nest/docker.env
    ports:
      - '3000:3000'

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - '5050:80'
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
