/* eslint-disable canonical/sort-keys */
module.exports = [
  {
    name: 'default',
    type: 'postgres',
    host: process.env.POSTGRES_HOST_DEFAULT,
    port: process.env.POSTGRES_PORT_DEFAULT,
    username: process.env.POSTGRES_USER_DEFAULT,
    password: process.env.POSTGRES_PASSWORD_DEFAULT,
    database: process.env.POSTGRES_DB_DEFAULT,
    entities: ['dist/infrastructure/entity/*.entity.js'],
    migrations: ['dist/database/migrations/*.{js,ts}'],
    factories: ['dist/database/factories/*.factory.js'],
    seeds: ['dist/database/seeds/*.seed.js'],
    synchronize: true,
    autoLoadEntities: true,
  },
  {
    name: 'test',
    type: 'postgres',
    host: process.env.POSTGRES_HOST_TEST,
    port: process.env.POSTGRES_PORT_TEST,
    username: process.env.POSTGRES_USER_TEST,
    password: process.env.POSTGRES_PASSWORD_TEST,
    database: process.env.POSTGRES_DB_TEST,
    entities: ['dist/infrastructure/entity/*.entity.js'],
    migrations: ['dist/database/migrations/*.{js,ts}'],
    factories: ['dist/database/factories/*.factory.js'],
    seeds: ['dist/database/seeds/*.seed.js'],
    synchronize: true,
    autoLoadEntities: true,
  },
];
