# stage 1: Development
FROM node:20-alpine as dev

WORKDIR /improve

ENV NODE_ENV development
RUN apk add --no-cache libc6-compat
RUN adduser -S -u 1001 -G node myuser
ENV PATH="/home/myuser/.yarn/bin:$PATH"

COPY --chown=node:node . /improve

USER myuser

CMD yarn install && yarn start:dev