name: TEST

on:
  push:
    branches:
      - feature/*
      - fix/*
      - hotfix/*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Yarn
      run: npm i -g yarn

    - name: Install Dependencies
      run: yarn install

    - name: Wait for PostgreSQL to start
      run: |
        while ! pg_isready -U postgres -h localhost -p 5432 > /dev/null 2> /dev/null; do
          echo "$(date) - waiting for database to start"
          sleep 2
        done  

    - name: Run migrations
      run: yarn typeorm migration:run

    - name: Run tests
      run: yarn test
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DB_DATABASE_NAME: test